### ISSUE TITLE
Comparison to other communication middleware

### ISSUE THREAD

**Issue by weberdaniel** [entc/qbus#1]
Dear ladies and gentlemen,

What is the Userbase of the QORE/QBus libraries?

What is the advantage of QORE/QBus in comparison to communication middleware such as

    C++ Actor Framework (github.com/actor-framework)
    POCO ( https://pocoproject.org/ )
    ACE (https://www.dre.vanderbilt.edu/~schmidt/ACE.html )

Is this a valid communication library for an operational setup or is it an experimental library?

Kind regards,
Daniel Weber

**Comment by entc** [comment]
Hello Daniel,

thanks for the interest and comment. The QBUS library is not addressing to be a communication middleware in the classic way. The library was designed to provide the communication between dedicated programs. This has been done by exchanging messages addressing methods in each program. This can be compared to a classic RPC approach. The default engine used to transport those messages is based on the cape's asyncronous IO classes and using TCP as the transport layer. The design is fully event driven, and each event can be considered as a remote function call. The application logic can follow a single event or a chain of events. Each event is an own entity to avoid locking mechanisms or syncronisation.
Assuming the frameworks above are providing a similar functionality, a C based library can considered as more lightweight and easier to link into your project. Also the use of the cape library and their direct approach with the OS makes it an efficient way with a low footprint. The API is easy to understand and simple.

The library is in production state and used by several projects.

Cheers
